[pyprland]
plugins = [
 "scratchpads",
 "shift_monitors",
 "toggle_special",
]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "alacritty --class"
passwordManager_classed = "keepassxc --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.password-manager]
animation = "fromTop"
command = "/etc/profiles/per-user/ranjit/bin/keepassxc"
class = "org.keepassxc.KeePassXC" 
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.zapzap]
animation = "fromTop"
command = "/etc/profiles/per-user/ranjit/bin/zapzap --class"
class = "ZapZap"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.signal]
animation = "fromTop"
command = "/etc/profiles/per-user/ranjit/bin/signal-desktop --class"
class = "signal-desktop"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.gucharmap]
animation = "fromTop"
command = "/etc/profiles/per-user/ranjit/bin/gucharmap "
class = "gucharmap"
size = "75% 60%"
max_size = "1920px 100%"


[scratchpads.youtube-music]
animation = "fromTop"
command = "/etc/profiles/per-user/ranjit/bin/youtube-music "
class = "com.github.th_ch.youtube_music"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.pavucontrol]
animation = "fromTop"
command = "/etc/profiles/per-user/ranjit/bin/pavucontrol "
class = "org.pulseaudio.pavucontrol"
size = "75% 60%"
max_size = "1920px 100%"

#[scratchpads.firefox]
#animation = "fromTop"
#command = "/etc/profiles/per-user/ranjit/bin/firefox --new-instance --browser --class"
#class = "firefox"
#size = "75% 60%"
#max_size = "1920px 100%"

[scratchpads.dolphin]
animation = "fromTop"
command = "dolphin"
class = "org.kde.dolphin"
size = "75% 60%"
max_size = "1920px 100%"
